# Generated by Django 5.2.7 on 2025-10-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_licencia', models.CharField(max_length=100, verbose_name='número de licencia')),
                ('categoria_licencia', models.CharField(max_length=50, verbose_name='categoría licencia')),
                ('vencimiento_licencia', models.DateField(verbose_name='vencimiento licencia')),
                ('autorizado', models.BooleanField(default=True, verbose_name='autorizado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'operador',
                'verbose_name_plural': 'operadores',
            },
        ),
    ]
