# Generated by Django 5.2.7 on 2025-10-16 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True, verbose_name='placa')),
                ('tipo', models.CharField(max_length=50, verbose_name='tipo')),
                ('capacidad', models.PositiveIntegerField(verbose_name='capacidad')),
                ('soat_vencimiento', models.DateField(verbose_name='SOAT - vencimiento')),
                ('tecnomecanica_vencimiento', models.DateField(verbose_name='Tecnomecánica - vencimiento')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
            },
        ),
    ]
