# Generated by Django 5.2.7 on 2025-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=255, verbose_name='acción')),
                ('tipo_objeto', models.CharField(blank=True, max_length=100, verbose_name='tipo_objeto')),
                ('objeto_id', models.CharField(blank=True, max_length=100, verbose_name='objeto_id')),
                ('datos', models.JSONField(blank=True, null=True, verbose_name='datos')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'registro de operación',
                'verbose_name_plural': 'registros de operación',
            },
        ),
    ]
