# Generated by Django 5.2.7 on 2025-11-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('operadores', '0001_initial'),
        ('vehiculos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='precio')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('segundos_validez', models.IntegerField(default=86400, verbose_name='segundos validez')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('expira_en', models.DateTimeField(blank=True, null=True, verbose_name='expira en')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('expirada', 'Expirada'), ('aceptada', 'Aceptada'), ('bloqueada', 'Bloqueada')], default='activa', max_length=20, verbose_name='estado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operadores.operador')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehiculos.vehiculo')),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('firmado', models.BooleanField(default=False, verbose_name='firmado')),
                ('oferta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='solicitudes.oferta')),
            ],
            options={
                'verbose_name': 'contrato',
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=255, verbose_name='origen')),
                ('destino', models.CharField(max_length=255, verbose_name='destino')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('pasajeros', models.PositiveIntegerField(verbose_name='pasajeros')),
                ('region', models.CharField(max_length=100, verbose_name='región')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_curso', 'En curso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=30, verbose_name='estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'solicitud',
                'verbose_name_plural': 'solicitudes',
            },
        ),
        migrations.AddField(
            model_name='oferta',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='solicitudes.solicitud'),
        ),
    ]
