# Generated by Django 5.2.7 on 2025-10-16 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=50, unique=True, verbose_name='NIT')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('representante', models.CharField(max_length=200, verbose_name='representante')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validada', 'Validada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='estado')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
            },
        ),
    ]
